compare.sh, include/isincidrange.sh, mkblocks.sh, runspftools.sh
Thanks for patches! Feel free to create a pull-request yourself next time.
=> Merging back

circle.yml, misc/circle-setup.sh, tests/test-real.sh, tests/test-shell.sh, tests/test-unit.sh
Fix tests to make them reliable (e.g. sort the output of dig).
Add ksh as possible shell (pdksh from loksh installs as /bin/bin/ksh).
=> Add circle.yml

normalize.sh
This will mitigate issue #28.
Just ./despf.sh domain |  ./normalize.sh
=> A script to normalize the network part of a CIDR

despf.sh, tests/nospf/cmd
Fixes issue
despf.sh fails silently #33
=> Return 1 on empty output

README.md
=> Add dependencies of cloudflare.sh to README

mkblocks.sh
=> Write the error message on stderr

include/despf.inc.sh, tests/test-unit.sh
Test included. In order to fix #50.
=> Add iteration for other NS servers

AUTHORS, LICENSE, README.md, cloudflare.sh, compare.sh, despf.sh, genspfzone.sh, include/despf.inc.sh, include/isincidrange.sh, misc/ci-setup.sh, misc/tmpl, mkblocks.sh, mkzoneent.sh, normalize.sh, runspftools.sh, tests/test-real.sh, tests/test-shell.sh, tests/test-unit.sh, xsel.sh
In order to address GitHub Issue #61
=> Apache2 License

include/isincidrange.sh, tests/test-shell.sh, tests/test-unit.sh
=> isincidrange.sh: Fix /32 case and add tests

README.md
Previous change broke the link and didn't fix the picture.
=> Fix TravisCI

README.md
tac was replaced with sed in
a15746fae360bf7ea42439a45f9930378060a85b
=> README: Do not mention unused tac

compare.sh, despf.sh, include/isincidrange.sh, tests/test-real.sh, tests/test-shell.sh
Now really all the scripts are run in debug mode
when environment variable DEBUG is set.
=> Extend debugging even more

include/despf.inc.sh, tests/test-unit.sh
Following functions were added:
- checkval4
- checkval6
- canon6
- shorten6 (unused)
Includes unit tests
Fixes GitHub issue #48
=> Implement address checking for both v4 and v6

AUTHORS
Not just feed-back, but there are also commits from
@TheNoButton and @regnauld.
=> Rearrange AUTHORS a bit

misc/ci-setup.sh, tests/test-shell.sh, tests/test-subdirs.sh, tests/test-unit.sh
=> Make test scripts executable

include/despf.inc.sh
This will allow #91 
Needs tests and documentation
=> Allows a list of domains not to be expanded in include

README.md, despf.sh, include/despf.inc.sh, misc/ci-runtest.sh, misc/ci-setup.sh, tests/brokendns/cmd, tests/test-unit.sh
This reverts commit 9d3bff64703da146d697649b20bb75ea02b5b691.
It came into master by error. Sorry.
=> Revert "Use drill instead of dig"

README.md, mkblocks.sh
As suggested by J. Barry Gurdin, Ph.D.
=> Change lookup to look-up

.travis.yml, misc/ci-runtest.sh
=> Fix coverage tests in Travis CI

.travis.yml
=> Update rvm to 2.3.0

.circleci/config.yml, README.md
https://github.com/spf-tools/spf-tools
=> Move to spf-tools organization

.travis.yml, misc/ci-runtest.sh, route53.sh
Force bashcov to v 1.8.2 and user Ruby 2.6
=> Fix Travis build

cloudflare.sh, compare.sh, despf.sh, genspfzone.sh, include/despf.inc.sh, xsel.sh
Addresses #175
All the .sh files can be checked like this:
```
git ls-files -- "*.sh" | xargs shellcheck
```
=> shellcheck fixes

despf.sh
=> despf.sh: Warn on missing command

AUTHORS, README.md, dnsimple.sh
The PR adds a script `dnsimple.sh`:
* Creates or updates DNS records at DNSimple
* Loosely based on the `cloudflare.sh` script
=> Add DNSimple update script
