tests/test-shell.sh

```
$ tests/test-shell.sh
Using /usr/bin/sh
BASH_VERSION='4.3.39(1)-release'
.. Testing ./simplify
.. OK
.. Testing ./mkblocks
.. OK
Using /usr/local/bin/pdksh
KSH_VERSION='@(#)PD KSH v5.2.14 99/07/13.2'
.. Testing ./simplify
.. OK
.. Testing ./mkblocks
.. OK
Using /usr/bin/bash
BASH_VERSION='4.3.39(1)-release'
.. Testing ./simplify
.. OK
.. Testing ./mkblocks
.. OK
Using /usr/bin/dash
.. Testing ./simplify
.. OK
.. Testing ./mkblocks
.. OK
Using /usr/bin/ash
.. Testing ./simplify
.. OK
.. Testing ./mkblocks
.. OK
Using /usr/bin/mksh
KSH_VERSION='@(#)MIRBSD KSH R50 2015/04/19'
.. Testing ./simplify
.. OK
.. Testing ./mkblocks
.. OK
```

Be less verbose if particular shell is not found

---

include/despf.inc.sh

Proper handling of a and mx modifiers to cover cases like this :a a:gnu.org a:google.com/24
Discard CNAME form lookups
printip adds CDIR net mask
Search for "v=spv1 " ( with space) at the beginning of the record for RFC compliance.

v=spf1 must have a space. Proper handling of a and mx modifier

---

include/despf.inc.sh

Fix for /jsarenik/spf-tools/#49 .
Proper handling of  "a/24" and "mx/20"

Fix for /jsarenik/spf-tools/#49

---

include/despf.inc.sh

This fixes #53 and is more general than
`grep -v "retrying in TCP mode"`

findns: Filter out comments on stdout

---

include/despf.inc.sh
normalize.sh

84b95a9 (Jan Sarenik, 33 seconds ago)
normalize.sh: Get rid of redundant variable
0692c8f (Jan Sarenik, 63 seconds ago)
despf.inc: Get rid of redundant grep

Cleanup Changes:

---

include/despf.inc.sh
tests/test-unit.sh

It seems that querying the authoritative nameserver
for the domain is not generally supported during tough
times.

Get rid of findns

---

AUTHORS

I know this may look like a duplicity, but in long term
it allows this repository to remember people even without
GitHub. Until then, live long GitHub!

AUTHORS: add @TheNoButton and @regnauld

---

misc/ci-runtest.sh
misc/ci-setup.sh

Do not compile everything from scratch but rather use
statically compiled binaries (x86_64, musl).

misc/ci: Simplify setup using statically linked bins

---

README.md
cloudflare.sh
compare.sh
despf.sh
genspfzone.sh
include/despf.inc.sh
mkblocks.sh
tests/a24/cmd
tests/brokendns/cmd
tests/despf/cmd
tests/fix_32/cmd
tests/mx20/cmd
tests/nospf/cmd
tests/redirect/cmd
tests/test-unit.sh

On 05/23/2016 someone registered the domain spf-tools.ml
It was possible because I had it on a free plan. Lessons
learned, moving to energystan.com which I own.

Change spf-tools.ml for energystan.com

---

README.md

from https://archive.drone.io/login:
Deprecation Warning
The hosted version of Drone is being deprecated in favor of
the open source edition of drone[1]. The open source edition is
actively maintained and was re-built from scratch to use the Docker
engine. The closed sourced edition previously powering drone.io is
no longer being maintained.
[1] https://github.com/drone/drone

Drone.io has been deprecated

---

include/despf.inc.sh

The _exists_ mechanism is already skipped. The other common usage is in  _include_ , that is covered by the PR.

Fix for #133 . Skips in include: has a %{

---

route53.sh

This script will use the AWS CLI to update spf DNS records in Route53.
The AWS CLI requires IAM credentials which can be configured using
environment variables (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY),
or using the AWS configuration file (~/.aws/credentials).
The script is used inline with `mkblocks.sh` and requires a Hosted Zone ID
as the first parameter.
```
./despf.sh | ./simplify.sh | ./mkblocks.sh | ./route53.sh ABCXYZEXAMPLE
```
An optional `-t` parameter can be specified to change the TTL.

Add AWS route53 DNS updating script

---

tests/test-subdirs.sh

The version of mktemp on Mac OS is not compatible with versions on
linux distributions. It requires either a template or a template prefix.
This change will supply a template prefix if running the plain mktemp fails
while executing the subdir tests.
http://unix.stackexchange.com/questions/30091/fix-or-alternative-for-mktemp-in-os-x

Fix the usage of mktemp on Mac OS

---

mkblocks.sh
tests/mkblocks-help/out

Add option to postfix the DNS name in addition to the existing prefix.  This allows us to do things like:
_1.spf.domain.com

Add suffix option

---

README.md
route53.sh

route53.sh should _not_ use mkzoneent.sh; fixes README and route53.sh docs.

Doc fixes for route53

---

README.md
cloudflare.sh

Fixes https://github.com/spf-tools/spf-tools/issues/164
Adds support for basic token verification: If run with
./cloudflare.sh verify
The only needed permissions for a custom API token are:
- Zone.Zone: Read
- Zone.DNS: Edit

cloudflare.sh: Fix the script and add verification

---

README.md
cloudflare.sh

Since Auth Bearer the EMAIL variable is not used at all
so the script should not check it exists. Updated README.md
as well.

cloudflare.sh: Get rid of EMAIL

---

cloudflare.sh

Only edit existing TXT records containig the "v=spf1" marker
If the root DNS contains multiple TXT records, the current code leads to malformed ids

Cloudflare: Filter the existing dns_records IDs for SPF records

---

README.md
shippable.yml

Shippable was acquired by JFrog
https://jfrog.com/pipelines/
https://jfrog.com/pricing/
http://blog.shippable.com/the-next-step-in-the-evolution-of-shippable-jfrog-pipelines
http://blog.shippable.com/migrating-from-shippable-to-jfrog-pipelines

Remove Shippable CI

---

mkblocks.sh
tests/mkblocks-help/out

A needed feature for me, so feel it could be useful for others as well.
My reasoning for this is as follows;
The core domain I'm need SPF flattening for is registered to a provider who doesn't provide an API access for record changes.
Therefore, I'd like to reuse a secondary domain I have hosted on another provider (with API access) to host these records.
This secondary domain already has an existing SPF record which I don't want to interfere with.
Understand that there's a few ways around this, like a subdomain prefix or simply transferring the domain to the API provider, but this method is the most suitable at the moment.

mkblocks: Provide an option to force prefix numbering on the first block.

---

mkblocks.sh

When an SPF record contains a macro (such as `%{ir}.%{v}.example.com`), mkblocks.sh fails with: 
```
./mkblocks.sh: line 116: printf: `{': invalid format character
```
This fixes the printf call, adding a simple format argument of `"%s"` so that printf does not try to treat the printed value as a format string.

Fix printf error when record contains macros

---

include/despf.inc.sh

seen using postwhite
grep (GNU grep) 3.11

grep: warning: stray \ before /
